version: "3.9"
services:
  db:
    container_name: "db"
    restart: "always"
    image: "postgres:latest"
    env_file:
      - "./.postgres.env"
    volumes:
      - "./db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
