version: "3.9"
services:
  db:
    container_name: "db"
    restart: "always"
    image: "postgres:latest"
    env_file:
      - "../.postgres.env"
    volumes:
      - "/home/ubuntu/db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  bot:
    container_name: "bot"
    restart: "always"
    build:
      context: "../"
      dockerfile: "./deployment/bot.dockerfile"
      args:
        - "PORT=3000"
    depends_on:
      - "db"
    env_file:
      - "../.env"
    ports:
      - "3000:3000"
  nginx:
    container_name: "nginx"
    restart: "always"
    build:
      context: "../"
      dockerfile: "./deployment/nginx.dockerfile"
    depends_on:
      - "bot"
    env_file:
      - "../.nginx.env"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/ubuntu/nginx_secrets:/etc/letsencrypt"
      - "/home/ubuntu/nginx_config:/etc/nginx/user_conf.d:ro"
