version: "3.9"
services:
  bot:
    container_name: "bot"
    restart: "always"
    build:
      context: "../"
      dockerfile: "./deployment/bot.dockerfile"
      args:
        - "PORT=3000"
    env_file:
      - "../.env"
    ports:
      - "3000:3000"
  nginx:
    container_name: "nginx"
    restart: "always"
    build:
      context: "../"
      dockerfile: "./deployment/nginx.dockerfile"
    env_file:
      - "../.nginx.env"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/ubuntu/nginx_secrets:/etc/letsencrypt"
      - "/home/ubuntu/nginx_config:/etc/nginx/user_conf.d:ro"
